server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com:7002  #eureka服务器端的实例名称
  client:
    #false表示是不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心 我的职责就是维护实例和服务  并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置于eureka service交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
