server:
  port: 8001
spring:
  application:
    name: cloud-payment-service


  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样值介于0到1之间，1表示全部采样
      probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    #表示是否向注册中心注册自己
    register-with-eureka: true
    #是否从eurekaservice抓取已有的注册信息 默认为true 单节点无所谓，集群必须使用true才能配合ribbon使用负载均衡
    fetch-registry: true
    #（入住）注册的地址
    service-url:
#      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/  #集群版
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #访问路径可以显示ip地址
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true  #访问路径可以显示ip地址
#    #eureka向服务端发送心跳间隔一秒（默认30s）
#    lease-renewal-interval-in-seconds: 1
#    #eureka最后一次收到心跳等待的时间上线二秒，超时将删除服务
#    lease-expiration-duration-in-seconds: 2

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities
