server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment-routh #payment_rout    #路由的id没有固定规则 但要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          #断言路径相匹配的进行路由
            - After=2022-05-14T14:17:25.121+08:00[Asia/Shanghai]  #当这个断言为true的时候gateway才正常启用
#            - Cookie=username,zzyy         #必须带有cookie 而且cookie的键值对为username,zzyy
#            - Header=X-Request-Id, \d+    #请求头要带有X-Request-Id属性 并且值为整数的正则表达式



        - id: payment-routh2 #payment_rout2   #路由的id没有固定规则 但要求唯一，建议配合服务名
#          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE     #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**          #断言路径相匹配的进行路由
            - After=2022-05-14T14:17:25.121+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy         #必须带有cookie 而且cookie的键值对为username,zzyy
#            - Header=X-Request-Id, \d+    #请求头要带有X-Request-Id属性 并且值为整数的正则表达式



eureka:
  instance:
    hostname: cloud-gateway-service  #eureka服务器端的实例名称
  client:  #服务提供者provider注册进服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      #单机之指向自己
      defaultZone: http://eureka7001.com:7001/eureka

#      集群指向其他eureka
#      设置于eureka service交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka

#  server:
#    #关闭自我保护机制 保证不可用服务被及时删除
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000

